services:
  - type: web
    name: mern-chat-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    rootDir: app/server
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: CLIENT_URL
        scope: build
      - key: MONGODB_URI
        scope: build
      - key: JWT_SECRET
        scope: build
      - key: LOG_LEVEL
        value: info
    autoDeploy: true
